;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	handle-switch-frame
	indent-for-tab-command
	kill-region
	move-lines-up
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-self-insert-command
	org-shiftright
	org-yank
	rjsx-electric-gt
	rjsx-electric-lt
	))

(setq mc/cmds-to-run-once
      '(
	compile
	eval-expression
	ido-find-file-other-window
	ido-switch-buffer
	mark-word-or-next-word-like-this
	mouse-save-then-kill
	mouse-set-region
	org-edit-src-save
	projectile-ripgrep
	projectile-switch-project
	save-and-export-to-pdf
	w32-drag-n-drop
	winner-undo
	))
