;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-lt-gt
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	comment-line
	comment-region
	duplicate-line
	ignore
	indent-for-tab-command
	insert-char
	kill-region
	move-lines-down
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-kill-line
	org-return
	org-self-insert-command
	org-yank
	typescript-insert-and-autoconvert-to-template
	typescript-insert-and-indent
	))

(setq mc/cmds-to-run-once
      '(
	handle-switch-frame
	mark-word-or-next-word-like-this
	org-fill-paragraph
	save-and-find-build-script-and-compile
	treemacs-delete-other-windows
	))
