;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-brace
	c-electric-colon
	c-electric-lt-gt
	c-electric-paren
	c-electric-pound
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-indent-line-or-region
	comment-line
	comment-region
	duplicate-line
	ignore
	indent-for-tab-command
	insert-char
	kill-region
	markdown-outdent-or-delete
	move-lines-down
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-force-self-insert
	org-kill-line
	org-return
	org-self-insert-command
	org-yank
	orgtbl-self-insert-command
	rjsx-electric-gt
	rjsx-electric-lt
	typescript-insert-and-autoconvert-to-template
	typescript-insert-and-indent
	))

(setq mc/cmds-to-run-once
      '(
	change-lang
	counsel-M-x
	counsel-find-file
	describe-key
	emmet-expand-line
	handle-switch-frame
	ivy-switch-buffer
	mark-word-or-next-word-like-this
	markdown-cycle
	mouse-set-region
	org-fill-paragraph
	orgtbl-hijacker-command-109
	projectile-ripgrep
	save-and-find-build-script-and-compile
	swiper
	treemacs-delete-other-windows
	))
